; Generated by KLFC 1.5.6
; https://github.com/39aldo39/klfc

#MaxHotkeysPerInterval 200
#MaxThreadsPerHotkey 10

SendUps(ByRef modifiers) {
  for index, modifier in modifiers {
    if (modifier == "Caps")
      SetCapsLockState, off
    else if (modifier == "Num")
      SetNumLockState, off
    else if InStr(modifier, "Extend")
      %modifier% := false
    else
      Send {%modifier% Up}
  }
  modifiers := Object()
}

SendAsUnicode(string) {
  Result := ""
  Loop, Parse, string
    Result .= Format("{{}U+{:04x}{}}", Ord(A_LoopField))
  Send {Blind}%Result%
}

DeadKeys := ComObjCreate("Scripting.Dictionary")

DeadKey(baseChar, table, name := "") {
  Global ActiveDeadKey
  if (ActiveDeadKey != "") {
    NewActiveDeadKey := ComObjCreate("Scripting.Dictionary")
    for key in table {
      value := table.item(key)
      NewActiveDeadKey.item(key) := ActiveDeadKey.item(value)
    }
    result := ActiveDeadKey.item(name)
    if (IsObject(result)) {
      for key in result {
        value := result.item(key)
        NewActiveDeadKey.item(key) := value
      }
    } else if (result != "") {
      ActiveDeadKey := ""
      SendAsUnicode(result)
      Return
    }
    ActiveDeadKey := NewActiveDeadKey
    Return
  }
  ActiveDeadKey := table
  Input key, L1, {Esc}{F1}{F2}{F3}{F4}{F5}{F6}{F7}{F8}{F9}{F10}{F11}{F12}{Left}{Right}{Up}{Down}{Home}{End}{PgUp}{PgDn}{Del}{Ins}{BS}{PrintScreen}{Pause}{AppsKey}
  If InStr(ErrorLevel, "EndKey:") {
    ActiveDeadKey := ""
    value := SubStr(ErrorLevel, 8)
    Send {Blind}{%value%}
    SendAsUnicode(baseChar)
  } else if (ErrorLevel != "NewInput") {
    value := ActiveDeadKey.item(key)
    ActiveDeadKey := ""
    if (IsObject(value)) {
      DeadKey(baseChar, value)
    } else if (value != "") {
      SendAsUnicode(value)
    } else {
      SendAsUnicode(baseChar . key)
    }
  }
}

SC056::LShift ; QWERTY Iso
*SC029::Send {Blind}{VKc0SC029 DownR} ; QWERTY ~: ~
*SC029 up::Send {Blind}{VKc0SC029 Up}
*SC002::Send {Blind}{VK31SC002 DownR} ; QWERTY 1: 1
*SC002 up::Send {Blind}{VK31SC002 Up}
*SC003::Send {Blind}{VK32SC003 DownR} ; QWERTY 2: 2
*SC003 up::Send {Blind}{VK32SC003 Up}
*SC004::Send {Blind}{VK33SC004 DownR} ; QWERTY 3: 3
*SC004 up::Send {Blind}{VK33SC004 Up}
*SC005::Send {Blind}{VK34SC005 DownR} ; QWERTY 4: 4
*SC005 up::Send {Blind}{VK34SC005 Up}
*SC006::Send {Blind}{VK35SC006 DownR} ; QWERTY 5: 5
*SC006 up::Send {Blind}{VK35SC006 Up}
*SC007::Send {Blind}{VK36SC007 DownR} ; QWERTY 6: 6
*SC007 up::Send {Blind}{VK36SC007 Up}
*SC008::Send {Blind}{VK37SC008 DownR} ; QWERTY 7: 7
*SC008 up::Send {Blind}{VK37SC008 Up}
*SC009::Send {Blind}{VK38SC009 DownR} ; QWERTY 8: 8
*SC009 up::Send {Blind}{VK38SC009 Up}
*SC00a::Send {Blind}{VK39SC00a DownR} ; QWERTY 9: 9
*SC00a up::Send {Blind}{VK39SC00a Up}
*SC00b::Send {Blind}{VK30SC00b DownR} ; QWERTY 0: 0
*SC00b up::Send {Blind}{VK30SC00b Up}
*SC00c::Send {Blind}{VKbdSC00c DownR} ; QWERTY -: -
*SC00c up::Send {Blind}{VKbdSC00c Up}
*SC00d::Send {Blind}{VKbbSC00d DownR} ; QWERTY +: +
*SC00d up::Send {Blind}{VKbbSC00d Up}
*SC010::Send {Blind}{VK51SC010 DownR} ; QWERTY Q: Q
*SC010 up::Send {Blind}{VK51SC010 Up}
*SC011::Send {Blind}{VK57SC011 DownR} ; QWERTY W: W
*SC011 up::Send {Blind}{VK57SC011 Up}
*SC012::Send {Blind}{VK45SC012 DownR} ; QWERTY E: E
*SC012 up::Send {Blind}{VK45SC012 Up}
*SC013::Send {Blind}{VK52SC013 DownR} ; QWERTY R: R
*SC013 up::Send {Blind}{VK52SC013 Up}
*SC014::Send {Blind}{VK54SC014 DownR} ; QWERTY T: T
*SC014 up::Send {Blind}{VK54SC014 Up}
*SC015::Send {Blind}{VK59SC015 DownR} ; QWERTY Y: Y
*SC015 up::Send {Blind}{VK59SC015 Up}
*SC016::Send {Blind}{VK55SC016 DownR} ; QWERTY U: U
*SC016 up::Send {Blind}{VK55SC016 Up}
*SC017::Send {Blind}{VK49SC017 DownR} ; QWERTY I: I
*SC017 up::Send {Blind}{VK49SC017 Up}
*SC018::Send {Blind}{VK4fSC018 DownR} ; QWERTY O: O
*SC018 up::Send {Blind}{VK4fSC018 Up}
*SC019::Send {Blind}{VK50SC019 DownR} ; QWERTY P: P
*SC019 up::Send {Blind}{VK50SC019 Up}
*SC01a::Send {Blind}{VKdbSC01a DownR} ; QWERTY [: [
*SC01a up::Send {Blind}{VKdbSC01a Up}
*SC01b::Send {Blind}{VKddSC01b DownR} ; QWERTY ]: ]
*SC01b up::Send {Blind}{VKddSC01b Up}
*SC02b::Send {Blind}{VKdcSC02b DownR} ; QWERTY \: \
*SC02b up::Send {Blind}{VKdcSC02b Up}
*SC01e::Send {Blind}{VK41SC01e DownR} ; QWERTY A: A
*SC01e up::Send {Blind}{VK41SC01e Up}
*SC01f::Send {Blind}{VK53SC01f DownR} ; QWERTY S: S
*SC01f up::Send {Blind}{VK53SC01f Up}
*SC020::Send {Blind}{VK44SC020 DownR} ; QWERTY D: D
*SC020 up::Send {Blind}{VK44SC020 Up}
*SC021::Send {Blind}{VK46SC021 DownR} ; QWERTY F: F
*SC021 up::Send {Blind}{VK46SC021 Up}
*SC022::Send {Blind}{VK47SC022 DownR} ; QWERTY G: G
*SC022 up::Send {Blind}{VK47SC022 Up}
*SC023::Send {Blind}{VK48SC023 DownR} ; QWERTY H: H
*SC023 up::Send {Blind}{VK48SC023 Up}
*SC024::Send {Blind}{VK4aSC024 DownR} ; QWERTY J: J
*SC024 up::Send {Blind}{VK4aSC024 Up}
*SC025::Send {Blind}{VK4bSC025 DownR} ; QWERTY K: K
*SC025 up::Send {Blind}{VK4bSC025 Up}
*SC026::Send {Blind}{VK4cSC026 DownR} ; QWERTY L: L
*SC026 up::Send {Blind}{VK4cSC026 Up}
*SC027::Send {Blind}{VKbaSC027 DownR} ; QWERTY ;: ;
*SC027 up::Send {Blind}{VKbaSC027 Up}
*SC028::Send {Blind}{VKdeSC028 DownR} ; QWERTY ': '
*SC028 up::Send {Blind}{VKdeSC028 Up}
*SC02c::Send {Blind}{VK5aSC02c DownR} ; QWERTY Z: Z
*SC02c up::Send {Blind}{VK5aSC02c Up}
*SC02d::Send {Blind}{VK58SC02d DownR} ; QWERTY X: X
*SC02d up::Send {Blind}{VK58SC02d Up}
*SC02e::Send {Blind}{VK43SC02e DownR} ; QWERTY C: C
*SC02e up::Send {Blind}{VK43SC02e Up}
*SC02f::Send {Blind}{VK56SC02f DownR} ; QWERTY V: V
*SC02f up::Send {Blind}{VK56SC02f Up}
*SC030::Send {Blind}{VK42SC030 DownR} ; QWERTY B: B
*SC030 up::Send {Blind}{VK42SC030 Up}
*SC031::Send {Blind}{VK4eSC031 DownR} ; QWERTY N: N
*SC031 up::Send {Blind}{VK4eSC031 Up}
*SC032::Send {Blind}{VK4dSC032 DownR} ; QWERTY M: M
*SC032 up::Send {Blind}{VK4dSC032 Up}
*SC033::Send {Blind}{VKbcSC033 DownR} ; QWERTY ,: ,
*SC033 up::Send {Blind}{VKbcSC033 Up}
*SC034::Send {Blind}{VKbeSC034 DownR} ; QWERTY .: .
*SC034 up::Send {Blind}{VKbeSC034 Up}
*SC035::Send {Blind}{VKbfSC035 DownR} ; QWERTY /: /
*SC035 up::Send {Blind}{VKbfSC035 Up}
*SC039::Send {Blind}{VK20SC039 DownR} ; QWERTY Space: Space
*SC039 up::Send {Blind}{VK20SC039 Up}

; QWERTY ~
#if
SC029::Send {Blind}{U+0060} ; `
+SC029::Send {Blind}{U+007e} ; ~
^SC029::Return
>!<^SC029::
; grave
if (DeadKeys.item("grave") == "") {
  DeadKeys.item("grave") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("grave").item(" ") := "̀"
  DeadKeys.item("grave").item("A") := "À"
  DeadKeys.item("grave").item("a") := "à"
  DeadKeys.item("grave").item("E") := "È"
  DeadKeys.item("grave").item("e") := "è"
  DeadKeys.item("grave").item("I") := "Ì"
  DeadKeys.item("grave").item("i") := "ì"
  DeadKeys.item("grave").item("N") := "Ǹ"
  DeadKeys.item("grave").item("n") := "ǹ"
  DeadKeys.item("grave").item("O") := "Ò"
  DeadKeys.item("grave").item("o") := "ò"
  DeadKeys.item("grave").item("U") := "Ù"
  DeadKeys.item("grave").item("u") := "ù"
  DeadKeys.item("grave").item("W") := "Ẁ"
  DeadKeys.item("grave").item("w") := "ẁ"
  DeadKeys.item("grave").item("Y") := "Ỳ"
  DeadKeys.item("grave").item("y") := "ỳ"
}
DeadKey("``", DeadKeys.item("grave"), "grave")
Return
+>!<^SC029::
; tilde
if (DeadKeys.item("tilde") == "") {
  DeadKeys.item("tilde") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("tilde").item("=") := "≅"
  DeadKeys.item("tilde").item(" ") := "̃"
  DeadKeys.item("tilde").item("A") := "Ã"
  DeadKeys.item("tilde").item("a") := "ã"
  DeadKeys.item("tilde").item("E") := "Ẽ"
  DeadKeys.item("tilde").item("e") := "ẽ"
  DeadKeys.item("tilde").item("I") := "Ĩ"
  DeadKeys.item("tilde").item("i") := "ĩ"
  DeadKeys.item("tilde").item("N") := "Ñ"
  DeadKeys.item("tilde").item("n") := "ñ"
  DeadKeys.item("tilde").item("O") := "Õ"
  DeadKeys.item("tilde").item("o") := "õ"
  DeadKeys.item("tilde").item("U") := "Ũ"
  DeadKeys.item("tilde").item("u") := "ũ"
  DeadKeys.item("tilde").item("V") := "Ṽ"
  DeadKeys.item("tilde").item("v") := "ṽ"
  DeadKeys.item("tilde").item("Y") := "Ỹ"
  DeadKeys.item("tilde").item("y") := "ỹ"
}
DeadKey("~", DeadKeys.item("tilde"), "tilde")
Return

; QWERTY 1
#if
SC002::Send {Blind}{U+0031} ; 1
+SC002::Send {Blind}{U+0021} ; !
^SC002::Return
>!<^SC002::Send {Blind}{U+00a1} ; ¡
+>!<^SC002::Send {Blind}{U+00b9} ; ¹

; QWERTY 2
#if
SC003::Send {Blind}{U+0032} ; 2
+SC003::Send {Blind}{U+0040} ; @
^SC003::Return
>!<^SC003::Send {Blind}{U+00b2} ; ²
+>!<^SC003::
; doubleacute
if (DeadKeys.item("doubleacute") == "") {
  DeadKeys.item("doubleacute") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("doubleacute").item(" ") := "̋"
  DeadKeys.item("doubleacute").item("O") := "Ő"
  DeadKeys.item("doubleacute").item("o") := "ő"
  DeadKeys.item("doubleacute").item("U") := "Ű"
  DeadKeys.item("doubleacute").item("u") := "ű"
}
DeadKey("˝", DeadKeys.item("doubleacute"), "doubleacute")
Return

; QWERTY 3
#if
SC004::Send {Blind}{U+0033} ; 3
+SC004::Send {Blind}{U+0023} ; #
^SC004::Return
>!<^SC004::Send {Blind}{U+00b3} ; ³

; QWERTY 4
#if
SC005::Send {Blind}{U+0034} ; 4
+SC005::Send {Blind}{U+0024} ; $
^SC005::Return
>!<^SC005::Send {Blind}{U+00a3} ; £
+>!<^SC005::
; currency
if (DeadKeys.item("currency") == "") {
  DeadKeys.item("currency") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("currency").item(" ") := "¤"
  DeadKeys.item("currency").item("A") := "₳"
  DeadKeys.item("currency").item("a") := "؋"
  DeadKeys.item("currency").item("B") := "₱"
  DeadKeys.item("currency").item("b") := "฿"
  DeadKeys.item("currency").item("Ç") := "₵"
  DeadKeys.item("currency").item("C") := "₡"
  DeadKeys.item("currency").item("ç") := "₵"
  DeadKeys.item("currency").item("c") := "¢"
  DeadKeys.item("currency").item("D") := "₯"
  DeadKeys.item("currency").item("d") := "₫"
  DeadKeys.item("currency").item("E") := "₠"
  DeadKeys.item("currency").item("e") := "€"
  DeadKeys.item("currency").item("F") := "₣"
  DeadKeys.item("currency").item("f") := "ƒ"
  DeadKeys.item("currency").item("G") := "₲"
  DeadKeys.item("currency").item("g") := "₲"
  DeadKeys.item("currency").item("H") := "₴"
  DeadKeys.item("currency").item("h") := "₴"
  DeadKeys.item("currency").item("I") := "៛"
  DeadKeys.item("currency").item("i") := "﷼"
  DeadKeys.item("currency").item("K") := "₭"
  DeadKeys.item("currency").item("k") := "₭"
  DeadKeys.item("currency").item("L") := "₤"
  DeadKeys.item("currency").item("l") := "£"
  DeadKeys.item("currency").item("M") := "ℳ"
  DeadKeys.item("currency").item("m") := "₥"
  DeadKeys.item("currency").item("N") := "₦"
  DeadKeys.item("currency").item("n") := "₦"
  DeadKeys.item("currency").item("O") := "૱"
  DeadKeys.item("currency").item("o") := "௹"
  DeadKeys.item("currency").item("P") := "₧"
  DeadKeys.item("currency").item("p") := "₰"
  DeadKeys.item("currency").item("r") := "₢"
  DeadKeys.item("currency").item("R") := "₨"
  DeadKeys.item("currency").item("S") := "$"
  DeadKeys.item("currency").item("s") := "₪"
  DeadKeys.item("currency").item("T") := "₮"
  DeadKeys.item("currency").item("t") := "৳"
  DeadKeys.item("currency").item("Þ") := "৲"
  DeadKeys.item("currency").item("þ") := "৲"
  DeadKeys.item("currency").item("U") := "圓"
  DeadKeys.item("currency").item("u") := "元"
  DeadKeys.item("currency").item("W") := "₩"
  DeadKeys.item("currency").item("w") := "₩"
  DeadKeys.item("currency").item("Y") := "円"
  DeadKeys.item("currency").item("y") := "¥"
}
DeadKey("¤", DeadKeys.item("currency"), "currency")
Return

; QWERTY 5
#if
SC006::Send {Blind}{U+0035} ; 5
+SC006::Send {Blind}{U+0025} ; %
^SC006::Return
>!<^SC006::Send {Blind}{U+20ac} ; €
+>!<^SC006::
; caron
if (DeadKeys.item("caron") == "") {
  DeadKeys.item("caron") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("caron").item(" ") := "̌"
  DeadKeys.item("caron").item("A") := "Ǎ"
  DeadKeys.item("caron").item("a") := "ǎ"
  DeadKeys.item("caron").item("C") := "Č"
  DeadKeys.item("caron").item("c") := "č"
  DeadKeys.item("caron").item("D") := "Ď"
  DeadKeys.item("caron").item("d") := "ď"
  DeadKeys.item("caron").item("E") := "Ě"
  DeadKeys.item("caron").item("e") := "ě"
  DeadKeys.item("caron").item("G") := "Ǧ"
  DeadKeys.item("caron").item("g") := "ǧ"
  DeadKeys.item("caron").item("H") := "Ȟ"
  DeadKeys.item("caron").item("h") := "ȟ"
  DeadKeys.item("caron").item("I") := "Ǐ"
  DeadKeys.item("caron").item("i") := "ǐ"
  DeadKeys.item("caron").item("j") := "ǰ"
  DeadKeys.item("caron").item("K") := "Ǩ"
  DeadKeys.item("caron").item("k") := "ǩ"
  DeadKeys.item("caron").item("L") := "Ľ"
  DeadKeys.item("caron").item("l") := "ľ"
  DeadKeys.item("caron").item("N") := "Ň"
  DeadKeys.item("caron").item("n") := "ň"
  DeadKeys.item("caron").item("O") := "Ǒ"
  DeadKeys.item("caron").item("o") := "ǒ"
  DeadKeys.item("caron").item("R") := "Ř"
  DeadKeys.item("caron").item("r") := "ř"
  DeadKeys.item("caron").item("S") := "Š"
  DeadKeys.item("caron").item("s") := "š"
  DeadKeys.item("caron").item("T") := "Ť"
  DeadKeys.item("caron").item("t") := "ť"
  DeadKeys.item("caron").item("U") := "Ǔ"
  DeadKeys.item("caron").item("u") := "ǔ"
  DeadKeys.item("caron").item("Z") := "Ž"
  DeadKeys.item("caron").item("z") := "ž"
  DeadKeys.item("caron").item("Ʒ") := "Ǯ"
  DeadKeys.item("caron").item("ʒ") := "ǯ"
}
DeadKey("ˇ", DeadKeys.item("caron"), "caron")
Return

; QWERTY 6
#if
SC007::Send {Blind}{U+0036} ; 6
+SC007::Send {Blind}{U+005e} ; ^
^SC007::Return
>!<^SC007::Send {Blind}{U+00bc} ; ¼
+>!<^SC007::
; circumflex
if (DeadKeys.item("circumflex") == "") {
  DeadKeys.item("circumflex") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("circumflex").item(" ") := "̂"
  DeadKeys.item("circumflex").item("A") := "Â"
  DeadKeys.item("circumflex").item("a") := "â"
  DeadKeys.item("circumflex").item("C") := "Ĉ"
  DeadKeys.item("circumflex").item("c") := "ĉ"
  DeadKeys.item("circumflex").item("E") := "Ê"
  DeadKeys.item("circumflex").item("e") := "ê"
  DeadKeys.item("circumflex").item("G") := "Ĝ"
  DeadKeys.item("circumflex").item("g") := "ĝ"
  DeadKeys.item("circumflex").item("H") := "Ĥ"
  DeadKeys.item("circumflex").item("h") := "ĥ"
  DeadKeys.item("circumflex").item("I") := "Î"
  DeadKeys.item("circumflex").item("i") := "î"
  DeadKeys.item("circumflex").item("J") := "Ĵ"
  DeadKeys.item("circumflex").item("j") := "ĵ"
  DeadKeys.item("circumflex").item("O") := "Ô"
  DeadKeys.item("circumflex").item("o") := "ô"
  DeadKeys.item("circumflex").item("S") := "Ŝ"
  DeadKeys.item("circumflex").item("s") := "ŝ"
  DeadKeys.item("circumflex").item("U") := "Û"
  DeadKeys.item("circumflex").item("u") := "û"
  DeadKeys.item("circumflex").item("W") := "Ŵ"
  DeadKeys.item("circumflex").item("w") := "ŵ"
  DeadKeys.item("circumflex").item("Y") := "Ŷ"
  DeadKeys.item("circumflex").item("y") := "ŷ"
  DeadKeys.item("circumflex").item("Z") := "Ẑ"
  DeadKeys.item("circumflex").item("z") := "ẑ"
}
DeadKey("^", DeadKeys.item("circumflex"), "circumflex")
Return

; QWERTY 7
#if
SC008::Send {Blind}{U+0037} ; 7
+SC008::Send {Blind}{U+0026} ; &
^SC008::Return
>!<^SC008::Send {Blind}{U+00bd} ; ½
+>!<^SC008::
; cedilla
if (DeadKeys.item("cedilla") == "") {
  DeadKeys.item("cedilla") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("cedilla").item(" ") := "̧"
  DeadKeys.item("cedilla").item("C") := "Ç"
  DeadKeys.item("cedilla").item("c") := "ç"
  DeadKeys.item("cedilla").item("D") := "Ḑ"
  DeadKeys.item("cedilla").item("d") := "ḑ"
  DeadKeys.item("cedilla").item("E") := "Ȩ"
  DeadKeys.item("cedilla").item("e") := "ȩ"
  DeadKeys.item("cedilla").item("G") := "Ģ"
  DeadKeys.item("cedilla").item("g") := "ģ"
  DeadKeys.item("cedilla").item("H") := "Ḩ"
  DeadKeys.item("cedilla").item("h") := "ḩ"
  DeadKeys.item("cedilla").item("K") := "Ķ"
  DeadKeys.item("cedilla").item("k") := "ķ"
  DeadKeys.item("cedilla").item("L") := "Ļ"
  DeadKeys.item("cedilla").item("l") := "ļ"
  DeadKeys.item("cedilla").item("N") := "Ņ"
  DeadKeys.item("cedilla").item("n") := "ņ"
  DeadKeys.item("cedilla").item("R") := "Ŗ"
  DeadKeys.item("cedilla").item("r") := "ŗ"
  DeadKeys.item("cedilla").item("S") := "Ş"
  DeadKeys.item("cedilla").item("s") := "ş"
  DeadKeys.item("cedilla").item("T") := "Ţ"
  DeadKeys.item("cedilla").item("t") := "ţ"
}
DeadKey("¸", DeadKeys.item("cedilla"), "cedilla")
Return

; QWERTY 8
#if
SC009::Send {Blind}{U+0038} ; 8
+SC009::Send {Blind}{U+002a} ; *
^SC009::Return
>!<^SC009::Send {Blind}{U+00be} ; ¾
+>!<^SC009::
; ogonek
if (DeadKeys.item("ogonek") == "") {
  DeadKeys.item("ogonek") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("ogonek").item(" ") := "̨"
  DeadKeys.item("ogonek").item("A") := "Ą"
  DeadKeys.item("ogonek").item("a") := "ą"
  DeadKeys.item("ogonek").item("E") := "Ę"
  DeadKeys.item("ogonek").item("e") := "ę"
  DeadKeys.item("ogonek").item("I") := "Į"
  DeadKeys.item("ogonek").item("i") := "į"
  DeadKeys.item("ogonek").item("O") := "Ǫ"
  DeadKeys.item("ogonek").item("o") := "ǫ"
  DeadKeys.item("ogonek").item("U") := "Ų"
  DeadKeys.item("ogonek").item("u") := "ų"
}
DeadKey("˛", DeadKeys.item("ogonek"), "ogonek")
Return

; QWERTY 9
#if
SC00a::Send {Blind}{U+0039} ; 9
+SC00a::Send {Blind}{U+0028} ; (
^SC00a::Return
>!<^SC00a::Send {Blind}{U+2018} ; ‘
+>!<^SC00a::
; breve
if (DeadKeys.item("breve") == "") {
  DeadKeys.item("breve") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("breve").item(" ") := "̆"
  DeadKeys.item("breve").item("A") := "Ă"
  DeadKeys.item("breve").item("a") := "ă"
  DeadKeys.item("breve").item("E") := "Ĕ"
  DeadKeys.item("breve").item("e") := "ĕ"
  DeadKeys.item("breve").item("G") := "Ğ"
  DeadKeys.item("breve").item("g") := "ğ"
  DeadKeys.item("breve").item("I") := "Ĭ"
  DeadKeys.item("breve").item("i") := "ĭ"
  DeadKeys.item("breve").item("O") := "Ŏ"
  DeadKeys.item("breve").item("o") := "ŏ"
  DeadKeys.item("breve").item("U") := "Ŭ"
  DeadKeys.item("breve").item("u") := "ŭ"
}
DeadKey("˘", DeadKeys.item("breve"), "breve")
Return

; QWERTY 0
#if
SC00b::Send {Blind}{U+0030} ; 0
+SC00b::Send {Blind}{U+0029} ; )
^SC00b::Return
>!<^SC00b::Send {Blind}{U+2019} ; ’
+>!<^SC00b::
; overring
if (DeadKeys.item("overring") == "") {
  DeadKeys.item("overring") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("overring").item(" ") := "̊"
  DeadKeys.item("overring").item("A") := "Å"
  DeadKeys.item("overring").item("a") := "å"
  DeadKeys.item("overring").item("U") := "Ů"
  DeadKeys.item("overring").item("u") := "ů"
  DeadKeys.item("overring").item("w") := "ẘ"
  DeadKeys.item("overring").item("y") := "ẙ"
}
DeadKey("˚", DeadKeys.item("overring"), "overring")
Return

; QWERTY -
#if
SC00c::Send {Blind}{U+002d} ; -
+SC00c::Send {Blind}{U+005f} ; _
^SC00c::Return
>!<^SC00c::Send {Blind}{U+00a5} ; ¥
+>!<^SC00c::
; macron
if (DeadKeys.item("macron") == "") {
  DeadKeys.item("macron") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("macron").item("<") := "≤"
  DeadKeys.item("macron").item(">") := "≥"
  DeadKeys.item("macron").item("+") := "±"
  DeadKeys.item("macron").item(" ") := "̄"
  DeadKeys.item("macron").item("A") := "Ā"
  DeadKeys.item("macron").item("a") := "ā"
  DeadKeys.item("macron").item("E") := "Ē"
  DeadKeys.item("macron").item("e") := "ē"
  DeadKeys.item("macron").item("G") := "Ḡ"
  DeadKeys.item("macron").item("g") := "ḡ"
  DeadKeys.item("macron").item("I") := "Ī"
  DeadKeys.item("macron").item("i") := "ī"
  DeadKeys.item("macron").item("O") := "Ō"
  DeadKeys.item("macron").item("o") := "ō"
  DeadKeys.item("macron").item("U") := "Ū"
  DeadKeys.item("macron").item("u") := "ū"
  DeadKeys.item("macron").item("Y") := "Ȳ"
  DeadKeys.item("macron").item("y") := "ȳ"
  DeadKeys.item("macron").item("Æ") := "Ǣ"
  DeadKeys.item("macron").item("æ") := "ǣ"
}
DeadKey("¯", DeadKeys.item("macron"), "macron")
Return

; QWERTY +
#if
SC00d::Send {Blind}{U+003d} ; =
+SC00d::Send {Blind}{U+002b} ; +
^SC00d::Return
>!<^SC00d::Send {Blind}{U+00d7} ; ×
+>!<^SC00d::Send {Blind}{U+00f7} ; ÷

; QWERTY Q
#if
SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0071} ; q
} else {
  Send {Blind}{U+0051} ; Q
}
Return
+SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0051} ; Q
} else {
  Send {Blind}{U+0071} ; q
}
Return
^SC010::Return
>!<^SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00e4} ; ä
} else {
  Send {Blind}{U+00c4} ; Ä
}
Return
+>!<^SC010::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00c4} ; Ä
} else {
  Send {Blind}{U+00e4} ; ä
}
Return

; QWERTY W
#if
SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0077} ; w
} else {
  Send {Blind}{U+0057} ; W
}
Return
+SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0057} ; W
} else {
  Send {Blind}{U+0077} ; w
}
Return
^SC011::Return
>!<^SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00e5} ; å
} else {
  Send {Blind}{U+00c5} ; Å
}
Return
+>!<^SC011::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00c5} ; Å
} else {
  Send {Blind}{U+00e5} ; å
}
Return

; QWERTY E
#if
SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0065} ; e
} else {
  Send {Blind}{U+0045} ; E
}
Return
+SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0045} ; E
} else {
  Send {Blind}{U+0065} ; e
}
Return
^SC012::Return
>!<^SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00e9} ; é
} else {
  Send {Blind}{U+00c9} ; É
}
Return
+>!<^SC012::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00c9} ; É
} else {
  Send {Blind}{U+00e9} ; é
}
Return

; QWERTY R
#if
SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0072} ; r
} else {
  Send {Blind}{U+0052} ; R
}
Return
+SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0052} ; R
} else {
  Send {Blind}{U+0072} ; r
}
Return
^SC013::Return
>!<^SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00ae} ; ®
} else {
  Send {Blind}{U+2122} ; ™
}
Return
+>!<^SC013::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+2122} ; ™
} else {
  Send {Blind}{U+00ae} ; ®
}
Return

; QWERTY T
#if
SC014::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0074} ; t
} else {
  Send {Blind}{U+0054} ; T
}
Return
+SC014::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0054} ; T
} else {
  Send {Blind}{U+0074} ; t
}
Return
^SC014::Return
>!<^SC014::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00fe} ; þ
} else {
  Send {Blind}{U+00de} ; Þ
}
Return
+>!<^SC014::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00de} ; Þ
} else {
  Send {Blind}{U+00fe} ; þ
}
Return

; QWERTY Y
#if
SC015::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0079} ; y
} else {
  Send {Blind}{U+0059} ; Y
}
Return
+SC015::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0059} ; Y
} else {
  Send {Blind}{U+0079} ; y
}
Return
^SC015::Return
>!<^SC015::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00fc} ; ü
} else {
  Send {Blind}{U+00dc} ; Ü
}
Return
+>!<^SC015::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00dc} ; Ü
} else {
  Send {Blind}{U+00fc} ; ü
}
Return

; QWERTY U
#if
SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0075} ; u
} else {
  Send {Blind}{U+0055} ; U
}
Return
+SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0055} ; U
} else {
  Send {Blind}{U+0075} ; u
}
Return
^SC016::Return
>!<^SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00fa} ; ú
} else {
  Send {Blind}{U+00da} ; Ú
}
Return
+>!<^SC016::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00da} ; Ú
} else {
  Send {Blind}{U+00fa} ; ú
}
Return

; QWERTY I
#if
SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0069} ; i
} else {
  Send {Blind}{U+0049} ; I
}
Return
+SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0049} ; I
} else {
  Send {Blind}{U+0069} ; i
}
Return
^SC017::Return
>!<^SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00ed} ; í
} else {
  Send {Blind}{U+00cd} ; Í
}
Return
+>!<^SC017::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00cd} ; Í
} else {
  Send {Blind}{U+00ed} ; í
}
Return

; QWERTY O
#if
SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006f} ; o
} else {
  Send {Blind}{U+004f} ; O
}
Return
+SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004f} ; O
} else {
  Send {Blind}{U+006f} ; o
}
Return
^SC018::Return
>!<^SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00f3} ; ó
} else {
  Send {Blind}{U+00d3} ; Ó
}
Return
+>!<^SC018::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00d3} ; Ó
} else {
  Send {Blind}{U+00f3} ; ó
}
Return

; QWERTY P
#if
SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0070} ; p
} else {
  Send {Blind}{U+0050} ; P
}
Return
+SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0050} ; P
} else {
  Send {Blind}{U+0070} ; p
}
Return
^SC019::Return
>!<^SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00f8} ; ø
} else {
  Send {Blind}{U+00d8} ; Ø
}
Return
+>!<^SC019::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00d8} ; Ø
} else {
  Send {Blind}{U+00f8} ; ø
}
Return

; QWERTY [
#if
SC01a::Send {Blind}{U+005b} ; [
+SC01a::Send {Blind}{U+007b} ; {
^SC01a::Send {Blind}{U+001b} ; 
>!<^SC01a::Send {Blind}{U+00ab} ; «
+>!<^SC01a::Send {Blind}{U+201c} ; “

; QWERTY ]
#if
SC01b::Send {Blind}{U+005d} ; ]
+SC01b::Send {Blind}{U+007d} ; }
^SC01b::Send {Blind}{U+001d} ; 
>!<^SC01b::Send {Blind}{U+00bb} ; »
+>!<^SC01b::Send {Blind}{U+201d} ; ”

; QWERTY \
#if
SC02b::Send {Blind}{U+005c} ; \
+SC02b::Send {Blind}{U+007c} ; |
^SC02b::Send {Blind}{U+001c} ; 
>!<^SC02b::Send {Blind}{U+00ac} ; ¬
+>!<^SC02b::Send {Blind}{U+00a6} ; ¦

; QWERTY A
#if
SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0061} ; a
} else {
  Send {Blind}{U+0041} ; A
}
Return
+SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0041} ; A
} else {
  Send {Blind}{U+0061} ; a
}
Return
^SC01e::Return
>!<^SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00e1} ; á
} else {
  Send {Blind}{U+00c1} ; Á
}
Return
+>!<^SC01e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00c1} ; Á
} else {
  Send {Blind}{U+00e1} ; á
}
Return

; QWERTY S
#if
SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0073} ; s
} else {
  Send {Blind}{U+0053} ; S
}
Return
+SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0053} ; S
} else {
  Send {Blind}{U+0073} ; s
}
Return
^SC01f::Return
>!<^SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00df} ; ß
} else {
  Send {Blind}{U+00a7} ; §
}
Return
+>!<^SC01f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a7} ; §
} else {
  Send {Blind}{U+00df} ; ß
}
Return

; QWERTY D
#if
SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0064} ; d
} else {
  Send {Blind}{U+0044} ; D
}
Return
+SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0044} ; D
} else {
  Send {Blind}{U+0064} ; d
}
Return
^SC020::Return
>!<^SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00f0} ; ð
} else {
  Send {Blind}{U+00d0} ; Ð
}
Return
+>!<^SC020::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00d0} ; Ð
} else {
  Send {Blind}{U+00f0} ; ð
}
Return

; QWERTY F
#if
SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0066} ; f
} else {
  Send {Blind}{U+0046} ; F
}
Return
+SC021::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0046} ; F
} else {
  Send {Blind}{U+0066} ; f
}
Return

; QWERTY G
#if
SC022::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0067} ; g
} else {
  Send {Blind}{U+0047} ; G
}
Return
+SC022::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0047} ; G
} else {
  Send {Blind}{U+0067} ; g
}
Return

; QWERTY H
#if
SC023::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0068} ; h
} else {
  Send {Blind}{U+0048} ; H
}
Return
+SC023::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0048} ; H
} else {
  Send {Blind}{U+0068} ; h
}
Return

; QWERTY J
#if
SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006a} ; j
} else {
  Send {Blind}{U+004a} ; J
}
Return
+SC024::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004a} ; J
} else {
  Send {Blind}{U+006a} ; j
}
Return

; QWERTY K
#if
SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006b} ; k
} else {
  Send {Blind}{U+004b} ; K
}
Return
+SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004b} ; K
} else {
  Send {Blind}{U+006b} ; k
}
Return
^SC025::Return
>!<^SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0153} ; œ
} else {
  Send {Blind}{U+0152} ; Œ
}
Return
+>!<^SC025::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0152} ; Œ
} else {
  Send {Blind}{U+0153} ; œ
}
Return

; QWERTY L
#if
SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006c} ; l
} else {
  Send {Blind}{U+004c} ; L
}
Return
+SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004c} ; L
} else {
  Send {Blind}{U+006c} ; l
}
Return
^SC026::Return
>!<^SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0142} ; ł
} else {
  Send {Blind}{U+0141} ; Ł
}
Return
+>!<^SC026::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0141} ; Ł
} else {
  Send {Blind}{U+0142} ; ł
}
Return

; QWERTY ;
#if
SC027::Send {Blind}{U+003b} ; ;
+SC027::Send {Blind}{U+003a} ; :
^SC027::Return
>!<^SC027::Send {Blind}{U+00b6} ; ¶
+>!<^SC027::Send {Blind}{U+00b0} ; °

; QWERTY '
#if
SC028::Send {Blind}{U+0027} ; '
+SC028::Send {Blind}{U+0022} ; "
^SC028::Return
>!<^SC028::
; acute
if (DeadKeys.item("acute") == "") {
  DeadKeys.item("acute") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("acute").item(" ") := "́"
  DeadKeys.item("acute").item("A") := "Á"
  DeadKeys.item("acute").item("a") := "á"
  DeadKeys.item("acute").item("Æ") := "Ǽ"
  DeadKeys.item("acute").item("æ") := "ǽ"
  DeadKeys.item("acute").item("C") := "Ć"
  DeadKeys.item("acute").item("c") := "ć"
  DeadKeys.item("acute").item("E") := "É"
  DeadKeys.item("acute").item("e") := "é"
  DeadKeys.item("acute").item("G") := "Ǵ"
  DeadKeys.item("acute").item("g") := "ǵ"
  DeadKeys.item("acute").item("I") := "Í"
  DeadKeys.item("acute").item("i") := "í"
  DeadKeys.item("acute").item("K") := "Ḱ"
  DeadKeys.item("acute").item("k") := "ḱ"
  DeadKeys.item("acute").item("L") := "Ĺ"
  DeadKeys.item("acute").item("l") := "ĺ"
  DeadKeys.item("acute").item("M") := "Ḿ"
  DeadKeys.item("acute").item("m") := "ḿ"
  DeadKeys.item("acute").item("N") := "Ń"
  DeadKeys.item("acute").item("n") := "ń"
  DeadKeys.item("acute").item("O") := "Ó"
  DeadKeys.item("acute").item("o") := "ó"
  DeadKeys.item("acute").item("Ø") := "Ǿ"
  DeadKeys.item("acute").item("ø") := "ǿ"
  DeadKeys.item("acute").item("P") := "Ṕ"
  DeadKeys.item("acute").item("p") := "ṕ"
  DeadKeys.item("acute").item("R") := "Ŕ"
  DeadKeys.item("acute").item("r") := "ŕ"
  DeadKeys.item("acute").item("S") := "Ś"
  DeadKeys.item("acute").item("s") := "ś"
  DeadKeys.item("acute").item("U") := "Ú"
  DeadKeys.item("acute").item("u") := "ú"
  DeadKeys.item("acute").item("W") := "Ẃ"
  DeadKeys.item("acute").item("w") := "ẃ"
  DeadKeys.item("acute").item("Y") := "Ý"
  DeadKeys.item("acute").item("y") := "ý"
  DeadKeys.item("acute").item("Z") := "Ź"
  DeadKeys.item("acute").item("z") := "ź"
}
DeadKey("´", DeadKeys.item("acute"), "acute")
Return
+>!<^SC028::
; diaeresis
if (DeadKeys.item("diaeresis") == "") {
  DeadKeys.item("diaeresis") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("diaeresis").item(" ") := "̈"
  DeadKeys.item("diaeresis").item("A") := "Ä"
  DeadKeys.item("diaeresis").item("a") := "ä"
  DeadKeys.item("diaeresis").item("E") := "Ë"
  DeadKeys.item("diaeresis").item("e") := "ë"
  DeadKeys.item("diaeresis").item("H") := "Ḧ"
  DeadKeys.item("diaeresis").item("h") := "ḧ"
  DeadKeys.item("diaeresis").item("I") := "Ï"
  DeadKeys.item("diaeresis").item("i") := "ï"
  DeadKeys.item("diaeresis").item("O") := "Ö"
  DeadKeys.item("diaeresis").item("o") := "ö"
  DeadKeys.item("diaeresis").item("t") := "ẗ"
  DeadKeys.item("diaeresis").item("U") := "Ü"
  DeadKeys.item("diaeresis").item("u") := "ü"
  DeadKeys.item("diaeresis").item("W") := "Ẅ"
  DeadKeys.item("diaeresis").item("w") := "ẅ"
  DeadKeys.item("diaeresis").item("X") := "Ẍ"
  DeadKeys.item("diaeresis").item("x") := "ẍ"
  DeadKeys.item("diaeresis").item("Y") := "Ÿ"
  DeadKeys.item("diaeresis").item("y") := "ÿ"
}
DeadKey("¨", DeadKeys.item("diaeresis"), "diaeresis")
Return

; QWERTY Z
#if
SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+007a} ; z
} else {
  Send {Blind}{U+005a} ; Z
}
Return
+SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+005a} ; Z
} else {
  Send {Blind}{U+007a} ; z
}
Return
^SC02c::Return
>!<^SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00e6} ; æ
} else {
  Send {Blind}{U+00c6} ; Æ
}
Return
+>!<^SC02c::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00c6} ; Æ
} else {
  Send {Blind}{U+00e6} ; æ
}
Return

; QWERTY X
#if
SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0078} ; x
} else {
  Send {Blind}{U+0058} ; X
}
Return
+SC02d::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0058} ; X
} else {
  Send {Blind}{U+0078} ; x
}
Return

; QWERTY C
#if
SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0063} ; c
} else {
  Send {Blind}{U+0043} ; C
}
Return
+SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0043} ; C
} else {
  Send {Blind}{U+0063} ; c
}
Return
^SC02e::Return
>!<^SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a9} ; ©
} else {
  Send {Blind}{U+00a2} ; ¢
}
Return
+>!<^SC02e::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00a2} ; ¢
} else {
  Send {Blind}{U+00a9} ; ©
}
Return

; QWERTY V
#if
SC02f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0076} ; v
} else {
  Send {Blind}{U+0056} ; V
}
Return
+SC02f::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0056} ; V
} else {
  Send {Blind}{U+0076} ; v
}
Return

; QWERTY B
#if
SC030::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0062} ; b
} else {
  Send {Blind}{U+0042} ; B
}
Return
+SC030::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+0042} ; B
} else {
  Send {Blind}{U+0062} ; b
}
Return

; QWERTY N
#if
SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006e} ; n
} else {
  Send {Blind}{U+004e} ; N
}
Return
+SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004e} ; N
} else {
  Send {Blind}{U+006e} ; n
}
Return
^SC031::Return
>!<^SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00f1} ; ñ
} else {
  Send {Blind}{U+00d1} ; Ñ
}
Return
+>!<^SC031::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+00d1} ; Ñ
} else {
  Send {Blind}{U+00f1} ; ñ
}
Return

; QWERTY M
#if
SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+006d} ; m
} else {
  Send {Blind}{U+004d} ; M
}
Return
+SC032::
if not GetKeyState("CapsLock", "T") {
  Send {Blind}{U+004d} ; M
} else {
  Send {Blind}{U+006d} ; m
}
Return
^SC032::Return
>!<^SC032::Send {Blind}{U+00b5} ; µ

; QWERTY ,
#if
SC033::Send {Blind}{U+002c} ; ,
+SC033::Send {Blind}{U+003c} ; <
^SC033::Return
>!<^SC033::Send {Blind}{U+00e7} ; ç
+>!<^SC033::Send {Blind}{U+00c7} ; Ç

; QWERTY .
#if
SC034::Send {Blind}{U+002e} ; .
+SC034::Send {Blind}{U+003e} ; >
^SC034::Return
>!<^SC034::
; underdot
if (DeadKeys.item("underdot") == "") {
  DeadKeys.item("underdot") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("underdot").item(" ") := "̣"
  DeadKeys.item("underdot").item("A") := "Ạ"
  DeadKeys.item("underdot").item("a") := "ạ"
  DeadKeys.item("underdot").item("B") := "Ḅ"
  DeadKeys.item("underdot").item("b") := "ḅ"
  DeadKeys.item("underdot").item("D") := "Ḍ"
  DeadKeys.item("underdot").item("d") := "ḍ"
  DeadKeys.item("underdot").item("E") := "Ẹ"
  DeadKeys.item("underdot").item("e") := "ẹ"
  DeadKeys.item("underdot").item("H") := "Ḥ"
  DeadKeys.item("underdot").item("h") := "ḥ"
  DeadKeys.item("underdot").item("I") := "Ị"
  DeadKeys.item("underdot").item("i") := "ị"
  DeadKeys.item("underdot").item("K") := "Ḳ"
  DeadKeys.item("underdot").item("k") := "ḳ"
  DeadKeys.item("underdot").item("L") := "Ḷ"
  DeadKeys.item("underdot").item("l") := "ḷ"
  DeadKeys.item("underdot").item("M") := "Ṃ"
  DeadKeys.item("underdot").item("m") := "ṃ"
  DeadKeys.item("underdot").item("N") := "Ṇ"
  DeadKeys.item("underdot").item("n") := "ṇ"
  DeadKeys.item("underdot").item("O") := "Ọ"
  DeadKeys.item("underdot").item("o") := "ọ"
  DeadKeys.item("underdot").item("R") := "Ṛ"
  DeadKeys.item("underdot").item("r") := "ṛ"
  DeadKeys.item("underdot").item("S") := "Ṣ"
  DeadKeys.item("underdot").item("s") := "ṣ"
  DeadKeys.item("underdot").item("T") := "Ṭ"
  DeadKeys.item("underdot").item("t") := "ṭ"
  DeadKeys.item("underdot").item("U") := "Ụ"
  DeadKeys.item("underdot").item("u") := "ụ"
  DeadKeys.item("underdot").item("V") := "Ṿ"
  DeadKeys.item("underdot").item("v") := "ṿ"
  DeadKeys.item("underdot").item("W") := "Ẉ"
  DeadKeys.item("underdot").item("w") := "ẉ"
  DeadKeys.item("underdot").item("Y") := "Ỵ"
  DeadKeys.item("underdot").item("y") := "ỵ"
  DeadKeys.item("underdot").item("Z") := "Ẓ"
  DeadKeys.item("underdot").item("z") := "ẓ"
}
DeadKey("ࠃ", DeadKeys.item("underdot"), "underdot")
Return
+>!<^SC034::
; overdot
if (DeadKeys.item("overdot") == "") {
  DeadKeys.item("overdot") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("overdot").item(" ") := "̇"
  DeadKeys.item("overdot").item("A") := "Ȧ"
  DeadKeys.item("overdot").item("a") := "ȧ"
  DeadKeys.item("overdot").item("B") := "Ḃ"
  DeadKeys.item("overdot").item("b") := "ḃ"
  DeadKeys.item("overdot").item("C") := "Ċ"
  DeadKeys.item("overdot").item("c") := "ċ"
  DeadKeys.item("overdot").item("D") := "Ḋ"
  DeadKeys.item("overdot").item("d") := "ḋ"
  DeadKeys.item("overdot").item("E") := "Ė"
  DeadKeys.item("overdot").item("e") := "ė"
  DeadKeys.item("overdot").item("F") := "Ḟ"
  DeadKeys.item("overdot").item("f") := "ḟ"
  DeadKeys.item("overdot").item("G") := "Ġ"
  DeadKeys.item("overdot").item("g") := "ġ"
  DeadKeys.item("overdot").item("H") := "Ḣ"
  DeadKeys.item("overdot").item("h") := "ḣ"
  DeadKeys.item("overdot").item("I") := "İ"
  DeadKeys.item("overdot").item("i") := "ı"
  DeadKeys.item("overdot").item("M") := "Ṁ"
  DeadKeys.item("overdot").item("m") := "ṁ"
  DeadKeys.item("overdot").item("N") := "Ṅ"
  DeadKeys.item("overdot").item("n") := "ṅ"
  DeadKeys.item("overdot").item("O") := "Ȯ"
  DeadKeys.item("overdot").item("o") := "ȯ"
  DeadKeys.item("overdot").item("P") := "Ṗ"
  DeadKeys.item("overdot").item("p") := "ṗ"
  DeadKeys.item("overdot").item("R") := "Ṙ"
  DeadKeys.item("overdot").item("r") := "ṙ"
  DeadKeys.item("overdot").item("S") := "Ṡ"
  DeadKeys.item("overdot").item("s") := "ṡ"
  DeadKeys.item("overdot").item("T") := "Ṫ"
  DeadKeys.item("overdot").item("t") := "ṫ"
  DeadKeys.item("overdot").item("W") := "Ẇ"
  DeadKeys.item("overdot").item("w") := "ẇ"
  DeadKeys.item("overdot").item("X") := "Ẋ"
  DeadKeys.item("overdot").item("x") := "ẋ"
  DeadKeys.item("overdot").item("Y") := "Ẏ"
  DeadKeys.item("overdot").item("y") := "ẏ"
  DeadKeys.item("overdot").item("Z") := "Ż"
  DeadKeys.item("overdot").item("z") := "ż"
}
DeadKey("˙", DeadKeys.item("overdot"), "overdot")
Return

; QWERTY /
#if
SC035::Send {Blind}{U+002f} ; /
+SC035::Send {Blind}{U+003f} ; ?
^SC035::Return
>!<^SC035::Send {Blind}{U+00bf} ; ¿
+>!<^SC035::
; solidus
if (DeadKeys.item("solidus") == "") {
  DeadKeys.item("solidus") := ComObjCreate("Scripting.Dictionary")
  DeadKeys.item("solidus").item("=") := "≠"
  DeadKeys.item("solidus").item("?") := "‽"
  DeadKeys.item("solidus").item("¿") := "⸘"
  DeadKeys.item("solidus").item(" ") := "̷"
  DeadKeys.item("solidus").item("O") := "Ø"
  DeadKeys.item("solidus").item("o") := "ø"
  DeadKeys.item("solidus").item("D") := "Đ"
  DeadKeys.item("solidus").item("d") := "đ"
  DeadKeys.item("solidus").item("H") := "Ħ"
  DeadKeys.item("solidus").item("h") := "ħ"
  DeadKeys.item("solidus").item("L") := "Ł"
  DeadKeys.item("solidus").item("l") := "ł"
  DeadKeys.item("solidus").item("T") := "Ŧ"
  DeadKeys.item("solidus").item("t") := "ŧ"
  DeadKeys.item("solidus").item("b") := "ƀ"
  DeadKeys.item("solidus").item("I") := "Ɨ"
  DeadKeys.item("solidus").item("z") := "ƶ"
  DeadKeys.item("solidus").item("G") := "Ǥ"
  DeadKeys.item("solidus").item("g") := "ǥ"
  DeadKeys.item("solidus").item("Ó") := "Ǿ"
  DeadKeys.item("solidus").item("ó") := "ǿ"
  DeadKeys.item("solidus").item("i") := "ɨ"
  DeadKeys.item("solidus").item("A") := "Ⱥ"
  DeadKeys.item("solidus").item("a") := "ⱥ"
  DeadKeys.item("solidus").item("B") := "Ƀ"
  DeadKeys.item("solidus").item("C") := "Ȼ"
  DeadKeys.item("solidus").item("c") := "ȼ"
  DeadKeys.item("solidus").item("E") := "Ɇ"
  DeadKeys.item("solidus").item("e") := "ɇ"
  DeadKeys.item("solidus").item(">") := "≯"
  DeadKeys.item("solidus").item("≥") := "≱"
  DeadKeys.item("solidus").item("J") := "Ɉ"
  DeadKeys.item("solidus").item("j") := "ɉ"
  DeadKeys.item("solidus").item("ɩ") := "ᵼ"
  DeadKeys.item("solidus").item("ȷ") := "ɟ"
  DeadKeys.item("solidus").item("<") := "≮"
  DeadKeys.item("solidus").item("≤") := "≰"
  DeadKeys.item("solidus").item("P") := "Ᵽ"
  DeadKeys.item("solidus").item("p") := "ᵽ"
  DeadKeys.item("solidus").item("R") := "Ɍ"
  DeadKeys.item("solidus").item("r") := "ɍ"
  DeadKeys.item("solidus").item("U") := "Ʉ"
  DeadKeys.item("solidus").item("u") := "ʉ"
  DeadKeys.item("solidus").item("Y") := "Ɏ"
  DeadKeys.item("solidus").item("y") := "ɏ"
}
DeadKey("/", DeadKeys.item("solidus"), "solidus")
Return

; QWERTY Space
#if
SC039::Send {Blind}{U+0020} ;  
+SC039::Send {Blind}{U+0020} ;  
^SC039::Send {Blind}{U+0020} ;  
>!<^SC039::Send {Blind}{U+00a0} ;  
+>!<^SC039::Send {Blind}{U+200b} ; ​
